# Vaultwarden - CT 103
# /srv/appdata/vaultwarden/docker-compose.yml

services:
  vaultwarden:
    image: vaultwarden/server:1.33.2
    container_name: vaultwarden
    environment:
      - DOMAIN=https://vault-rxfsys.duckdns.org
      - ADMIN_TOKEN=DEIN_ADMIN_TOKEN  # Argon2-Hash empfohlen
      - SIGNUPS_ALLOWED=false
      - WEBSOCKET_ENABLED=true
      - LOG_LEVEL=warn
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
    volumes:
      - ./data:/data
    ports:
      - "8081:80"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
